// Pin It clip manifest — curated + HEAD-verified by agents, 2026-08-01.
// Languages + wild English clips stream from public archives (Commons/LOC/gov, free licenses);
// SAA accent clips mirrored under CC BY-NC-SA; Arabic city clips mirrored from ARCADE (CC BY 4.0),
// gated by Whisper QC + Claude dialect/label judging. wild:true = spontaneous speech, dealt first.
window.CLIPS = {
  "languages": [
    {
      "id": "lang-kazakh",
      "label": "Kazakh",
      "lang": "Kazakh",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/08/Qazaqsha_zhyl_sanau.ogg/Qazaqsha_zhyl_sanau.ogg.mp3",
      "lat": 48,
      "lng": 66.9,
      "r": 1000,
      "size": 1893021,
      "hint": "A spoken Kazakh Wikipedia article about the traditional 12-year animal calendar (duration ~78s).",
      "attribution": "File:Qazaqsha zhyl sanau.ogg, Tmrtlght, CC BY-SA 4.0, Wikimedia Commons"
    },
    {
      "id": "lang-uzbek",
      "label": "Uzbek",
      "lang": "Uzbek",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a7/Jadidlar.ogg/Jadidlar.ogg.mp3",
      "lat": 41.3,
      "lng": 64.5,
      "r": 600,
      "size": 2716345,
      "hint": "A spoken Uzbek Wikipedia article about the Jadids, Central Asia's early-1900s reform movement (~156s).",
      "attribution": "File:Jadidlar.ogg, Panpanchik, CC BY-SA 4.0, Wikimedia Commons"
    },
    {
      "id": "lang-kyrgyz",
      "label": "Kyrgyz",
      "lang": "Kyrgyz",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/57/An_example_of_a_dialogue_in_Kyrgyz._Two_friends_are_communicating.wav/An_example_of_a_dialogue_in_Kyrgyz._Two_friends_are_communicating.wav.mp3",
      "lat": 41.7,
      "lng": 74.5,
      "r": 400,
      "size": 402422,
      "hint": "Two friends wishing each other good grades on their exams. NOTE: only 17.6s long, shorter than the 20s window.",
      "attribution": "File:An example of a dialogue in Kyrgyz. Two friends are communicating.wav, user ПервыйЧеловекВКосмосн, CC0, Wikimedia Commons"
    },
    {
      "id": "lang-turkish",
      "label": "Turkish",
      "lang": "Turkish",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/df/Birle%C5%9Fmi%C5%9F_Milletler_G%C3%BCvenlik_Konseyi.ogg/Birle%C5%9Fmi%C5%9F_Milletler_G%C3%BCvenlik_Konseyi.ogg.mp3",
      "lat": 39.5,
      "lng": 34.5,
      "r": 700,
      "size": 5564119,
      "hint": "A Turkish spoken-Wikipedia reading about the UN Security Council (~6.5 min).",
      "attribution": "File:Birleşmiş Milletler Güvenlik Konseyi.ogg, narrated by Elmacenderesi (Turkish Spoken Wikipedia), CC BY-SA 2.5, Wikimedia Commons"
    },
    {
      "id": "lang-persian-farsi",
      "label": "Persian (Farsi)",
      "lang": "Persian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/48/Nowruz-fa.ogg/Nowruz-fa.ogg.mp3",
      "lat": 32.5,
      "lng": 53.7,
      "r": 1500,
      "size": 29750113,
      "hint": "A Persian Wikipedia reading of the article on Nowruz, the Persian New Year (~30 min).",
      "attribution": "File:Nowruz-fa.ogg, Mehdi at Persian Wikipedia and fa.wikipedia contributors, CC BY-SA 3.0, Wikimedia Commons"
    },
    {
      "id": "lang-hindi",
      "label": "Hindi",
      "lang": "Hindi",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d8/Hi-Hind-Europiya_bhaashaa_parivaar_part1.ogg/Hi-Hind-Europiya_bhaashaa_parivaar_part1.ogg.mp3",
      "lat": 26.8,
      "lng": 80.9,
      "r": 800,
      "size": 11270282,
      "hint": "A Hindi Wikipedia reading about the Indo-European language family (~15.5 min).",
      "attribution": "File:Hi-Hind-Europiya bhaashaa parivaar part1.ogg, Magicalsaumy at hi.wikipedia, CC BY-SA 3.0, Wikimedia Commons"
    },
    {
      "id": "lang-bengali",
      "label": "Bengali",
      "lang": "Bengali",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e0/Dengue_Bengali_symptoms.ogg/Dengue_Bengali_symptoms.ogg.mp3",
      "lat": 23.5,
      "lng": 89,
      "r": 400,
      "size": 547757,
      "hint": "A Bengali explanation of dengue fever symptoms, recorded at a 2012 Spoken Wikipedia workshop (~71s).",
      "attribution": "File:Dengue Bengali symptoms.ogg, Priyanka Nag, CC BY-SA 3.0, Wikimedia Commons"
    },
    {
      "id": "lang-thai",
      "label": "Thai",
      "lang": "Thai",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/44/Th-Saman_Gunan.ogg/Th-Saman_Gunan.ogg.mp3",
      "lat": 15.5,
      "lng": 101,
      "r": 500,
      "size": 7305995,
      "hint": "A Thai spoken-Wikipedia article about Saman Kunan, the diver from the 2018 Tham Luang cave rescue (~11 min).",
      "attribution": "File:Th-Saman Gunan.ogg, speaker B20180 (Thai Spoken Wikipedia), CC BY-SA 4.0, Wikimedia Commons"
    },
    {
      "id": "lang-vietnamese",
      "label": "Vietnamese",
      "lang": "Vietnamese",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/87/B%C3%A0i_th%C6%A1_Ki%E1%BA%BFp_L%C6%B0u_Vong.wav/B%C3%A0i_th%C6%A1_Ki%E1%BA%BFp_L%C6%B0u_Vong.wav.mp3",
      "lat": 16.5,
      "lng": 107.6,
      "r": 700,
      "size": 1741427,
      "hint": "A recitation of the Vietnamese poem 'Kiếp Lưu Vong' (Life in Exile) (~71s).",
      "attribution": "File:Bài thơ Kiếp Lưu Vong.wav, Hoàng Kỳ bay (read by Nguyễn Viết Dũng), CC BY-SA 4.0, Wikimedia Commons"
    },
    {
      "id": "lang-japanese",
      "label": "Japanese",
      "lang": "Japanese",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/26/Ja-botchan_1-1_1-2.ogg/Ja-botchan_1-1_1-2.ogg.mp3",
      "lat": 36,
      "lng": 138,
      "r": 700,
      "size": 1200480,
      "hint": "This is the opening of Natsume Soseki's beloved 1906 novel Botchan, read aloud.",
      "attribution": "File:Ja-botchan 1-1 1-2.ogg, read by marsian, Wikimedia Commons, Public domain"
    },
    {
      "id": "lang-korean",
      "label": "Korean",
      "lang": "Korean",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/LibriVox_-_%ED%98%84%EC%A7%84%EA%B1%B4_%ED%94%BC%EC%95%84%EB%85%B8.ogg/LibriVox_-_%ED%98%84%EC%A7%84%EA%B1%B4_%ED%94%BC%EC%95%84%EB%85%B8.ogg.mp3",
      "lat": 36.5,
      "lng": 127.8,
      "r": 500,
      "size": 5442614,
      "hint": "A LibriVox reading of \"Piano\", a 1920s short story by colonial-era writer Hyun Jin-geon.",
      "attribution": "File:LibriVox - 현진건 피아노.ogg, read by Jessie Yun for LibriVox, Wikimedia Commons, Public domain"
    },
    {
      "id": "lang-mandarin-chinese",
      "label": "Mandarin Chinese",
      "lang": "Mandarin Chinese",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ed/Zh-PRC-Part1.ogg/Zh-PRC-Part1.ogg.mp3",
      "lat": 35,
      "lng": 110,
      "r": 1500,
      "size": 27007306,
      "hint": "A spoken Wikipedia recording of the article about the People's Republic of China.",
      "attribution": "File:Zh-PRC-Part1.ogg, spoken by Blueberry Yogurt, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-indonesian",
      "label": "Indonesian",
      "lang": "Indonesian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b1/Akhsinatun_Aisyah_kartinah.ogg/Akhsinatun_Aisyah_kartinah.ogg.mp3",
      "lat": -4,
      "lng": 112,
      "r": 1500,
      "size": 5287019,
      "hint": "A spoken Indonesian Wikipedia article about Kartinah, recorded by a volunteer narrator.",
      "attribution": "File:Akhsinatun Aisyah kartinah.ogg, by Akhsinatun Aisyah, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-tagalog",
      "label": "Tagalog",
      "lang": "Tagalog",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/98/Hep_C_tl.ogg/Hep_C_tl.ogg.mp3",
      "lat": 14.6,
      "lng": 121,
      "r": 400,
      "size": 2410225,
      "hint": "A Tagalog Wikipedia health article about hepatitis C, read aloud for the Spoken Wikipedia project.",
      "attribution": "File:Hep C tl.ogg, spoken by Sky Harbor, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-swahili",
      "label": "Swahili",
      "lang": "Swahili",
      "url": "https://voa-audio.voanews.eu/vsw/2024/12/30/5c65b6ce-21a8-489d-b57e-7ff41afeea48_48k.mp3",
      "lat": -6.2,
      "lng": 39,
      "r": 1200,
      "size": 5929113,
      "hint": "A VOA Swahili radio feature about diseases that had major impact on Africa.",
      "attribution": "Voice of America Swahili Service (voaswahili.com), U.S. government work, public domain"
    },
    {
      "id": "lang-yoruba",
      "label": "Yoruba",
      "lang": "Yoruba",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0f/Yoruba_Wiki_Radio_Program.ogg/Yoruba_Wiki_Radio_Program.ogg.mp3",
      "lat": 7.4,
      "lng": 3.9,
      "r": 500,
      "size": 4664417,
      "hint": "A radio program produced by the Yoruba Wikimedians User Group in Nigeria.",
      "attribution": "File:Yoruba Wiki Radio Program.ogg, Yoruba Wikimedians User Group, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-amharic",
      "label": "Amharic",
      "lang": "Amharic",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/da/Chegode_Meri_Biruh_1.wav/Chegode_Meri_Biruh_1.wav.mp3",
      "lat": 9.03,
      "lng": 38.74,
      "r": 600,
      "size": 11241379,
      "hint": "An interview with a poet of Qene, Ethiopia's tradition of improvised double-meaning poetry.",
      "attribution": "File:Chegode Meri Biruh 1.wav, Goethe-Institut Addis Ababa (qeneonnet.org), Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-somali",
      "label": "Somali",
      "lang": "Somali",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c9/Shaxmednuradc1.ogg/Shaxmednuradc1.ogg.mp3",
      "lat": 5,
      "lng": 46,
      "r": 800,
      "size": 1277318,
      "hint": "Sheikh Ahmed Nur giving a speech in Standard Somali, broadcast on Somali TV in 2012.",
      "attribution": "File:Shaxmednuradc1.ogg, SOMTV, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-hausa",
      "label": "Hausa",
      "lang": "Hausa",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4d/Yan_Ghana_A_Jamus.ogg/Yan_Ghana_A_Jamus.ogg.mp3",
      "lat": 12,
      "lng": 8.5,
      "r": 800,
      "size": 13539544,
      "hint": "A Hausa Wikipedia article read aloud by a native speaker; Hausa is West Africa's biggest trade language.",
      "attribution": "File:Yan Ghana A Jamus.ogg, spoken by DaSupremo (Hausa Wikipedia), Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-zulu",
      "label": "Zulu",
      "lang": "Zulu",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/How_to_brew_traditional_zulu_beer.ogg/How_to_brew_traditional_zulu_beer.ogg.mp3",
      "lat": -28.5,
      "lng": 31,
      "r": 400,
      "size": 9231838,
      "hint": "Two Zulu men explain how to brew umqombothi, traditional Zulu beer.",
      "attribution": "File:How to brew traditional zulu beer.ogg, recorded by Rebekahn, translation by Thandeka, Wikimedia Commons, CC BY-SA 3.0 / GFDL"
    },
    {
      "id": "lang-malagasy",
      "label": "Malagasy",
      "lang": "Malagasy",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1d/Antemoro_dialect_sample.ogg/Antemoro_dialect_sample.ogg.mp3",
      "lat": -21.5,
      "lng": 47.5,
      "r": 800,
      "size": 2321142,
      "hint": "Two women from Namorona in southeast Madagascar, speaking the Antemoro dialect of Malagasy.",
      "attribution": "File:Antemoro dialect sample.ogg, by Gazetiko, Wikimedia Commons, CC0"
    },
    {
      "id": "lang-russian",
      "label": "Russian",
      "lang": "Russian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d6/Ru-Apex_Legends.ogg/Ru-Apex_Legends.ogg.mp3",
      "lat": 55.75,
      "lng": 37.62,
      "r": 1500,
      "size": 4165311,
      "hint": "The article being read is the Russian Wikipedia page about the video game Apex Legends.",
      "attribution": "File:Ru-Apex Legends.ogg, speaker Sergey Nikolaev V., Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-ukrainian",
      "label": "Ukrainian",
      "lang": "Ukrainian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/99/UA_Magnetic_bearing.ogg/UA_Magnetic_bearing.ogg.mp3",
      "lat": 49,
      "lng": 31.4,
      "r": 600,
      "size": 2003532,
      "hint": "A Ukrainian Wikipedia volunteer reading the article about magnetic bearings.",
      "attribution": "File:UA Magnetic bearing.ogg, speaker User:Veeer, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-polish",
      "label": "Polish",
      "lang": "Polish",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a6/Pl-Richard_Bourke-article.ogg/Pl-Richard_Bourke-article.ogg.mp3",
      "lat": 52.06,
      "lng": 19.48,
      "r": 400,
      "size": 5631678,
      "hint": "A Polish reading of the article about Richard Bourke, a 19th-century governor of New South Wales.",
      "attribution": "File:Pl-Richard Bourke-article.ogg, Powerek38, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-greek",
      "label": "Greek",
      "lang": "Greek",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cf/Ell-article-Theoria_tou_Haous.ogg/Ell-article-Theoria_tou_Haous.ogg.mp3",
      "lat": 38.5,
      "lng": 23.5,
      "r": 400,
      "size": 7772568,
      "hint": "The article being read is about chaos theory (Θεωρία του Χάους).",
      "attribution": "File:Ell-article-Theoria tou Haous.ogg, GPoul, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-german",
      "label": "German",
      "lang": "German",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/27/De-Ahlemer_Turm.ogg/De-Ahlemer_Turm.ogg.mp3",
      "lat": 50.9,
      "lng": 10,
      "r": 600,
      "size": 4744205,
      "hint": "The article is about the Ahlemer Turm, a historic tower in Hanover.",
      "attribution": "File:De-Ahlemer Turm.ogg, speaker Jonsonr, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-french",
      "label": "French",
      "lang": "French",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e0/Arquebuse.ogg/Arquebuse.ogg.mp3",
      "lat": 48.86,
      "lng": 2.35,
      "r": 1500,
      "size": 6732125,
      "hint": "The article is about the arquebus, an early gunpowder firearm.",
      "attribution": "File:Arquebuse.ogg, Michel, Wikimedia Commons, CC BY 3.0"
    },
    {
      "id": "lang-spanish-colombia",
      "label": "Spanish (Colombia)",
      "lang": "Spanish",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/45/Comisi%C3%B3n_de_la_Verdad.wav/Comisi%C3%B3n_de_la_Verdad.wav.mp3",
      "lat": 4.65,
      "lng": -74.08,
      "r": 1500,
      "size": 4685455,
      "hint": "The article is about Colombia's Truth Commission, read by a Colombian Wikipedia volunteer.",
      "attribution": "File:Comisión de la Verdad.wav, Sebaskorrea5, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-portuguese-brazil",
      "label": "Portuguese (Brazil)",
      "lang": "Portuguese",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/44/Eslavos_da_%C3%81sia_Menor_vers%C3%A3o_RJ.ogg/Eslavos_da_%C3%81sia_Menor_vers%C3%A3o_RJ.ogg.mp3",
      "lat": -22.91,
      "lng": -43.2,
      "r": 1500,
      "size": 4787500,
      "hint": "This is explicitly the Rio de Janeiro accent version of the article on Slavs of Asia Minor.",
      "attribution": "File:Eslavos da Ásia Menor versão RJ.ogg, Eduardo P, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-italian",
      "label": "Italian",
      "lang": "Italian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/95/Itwiki-Fonni.ogg/Itwiki-Fonni.ogg.mp3",
      "lat": 41.9,
      "lng": 12.5,
      "r": 500,
      "size": 2868482,
      "hint": "The article is about Fonni, the highest-altitude town on the island of Sardinia.",
      "attribution": "File:Itwiki-Fonni.ogg, IDany97, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "lang-swedish",
      "label": "Swedish",
      "lang": "Swedish",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/8d/Sv-R%C3%B6deby-article.ogg/Sv-R%C3%B6deby-article.ogg.mp3",
      "lat": 59.33,
      "lng": 18.07,
      "r": 500,
      "size": 2737700,
      "hint": "The article is about Rödeby, a small town in Blekinge, southern Sweden.",
      "attribution": "File:Sv-Rödeby-article.ogg, Arrowkiwi, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-finnish",
      "label": "Finnish",
      "lang": "Finnish",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/17/Fi-Suomi_johdanto.ogg/Fi-Suomi_johdanto.ogg.mp3",
      "lat": 62,
      "lng": 26,
      "r": 400,
      "size": 2759587,
      "hint": "The speaker is reading the introduction of the Finnish Wikipedia article about Finland itself.",
      "attribution": "File:Fi-Suomi johdanto.ogg, Vassilik, Wikimedia Commons, CC BY-SA 3.0"
    },
    {
      "id": "lang-hungarian",
      "label": "Hungarian",
      "lang": "Hungarian",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3c/HunArtTorokorszag.ogg/HunArtTorokorszag.ogg.mp3",
      "lat": 47.5,
      "lng": 19.05,
      "r": 300,
      "size": 7503872,
      "hint": "A Hungarian reading of the Wikipedia article about Turkey (Törökország).",
      "attribution": "File:HunArtTorokorszag.ogg, Wikimedia Commons, CC BY-SA 3.0"
    }
  ],
  "accents": [
    {
      "id": "wild-thomastown-county-kilkenny-ireland",
      "label": "Thomastown, County Kilkenny, Ireland",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9c/2024-09-16_Patrick_Lalor_Ladywell.opus/2024-09-16_Patrick_Lalor_Ladywell.opus.mp3",
      "lat": 52.5264,
      "lng": -7.137,
      "r": 150,
      "size": 24002324,
      "wild": true,
      "hint": "A 94-year-old lifelong local telling stories about the holy well behind his house (14:46 total, pick any segment)",
      "attribution": "Oral history interview by A.-K. D., Wikimedia Commons (File:2024-09-16 Patrick Lalor Ladywell.opus), CC0"
    },
    {
      "id": "wild-liverpool-england",
      "label": "Liverpool, England",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ef/John_bishop_bbc_radio4_desert_island_discs_24_06_2012.flac/John_bishop_bbc_radio4_desert_island_discs_24_06_2012.flac.mp3",
      "lat": 53.4084,
      "lng": -2.9916,
      "r": 60,
      "size": 1022640,
      "wild": true,
      "hint": "Comedian reminiscing about school; 33s interview speech",
      "attribution": "BBC Radio 4 Desert Island Discs (24 June 2012), via Wikimedia Commons, CC BY 3.0"
    },
    {
      "id": "wild-linlithgow-central-scotland-uk",
      "label": "Linlithgow / Central Scotland, UK",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/77/Alex_Salmond_BBC_Radio4_Desert_Island_Discs_16_January_2011_b00xgs41.flac/Alex_Salmond_BBC_Radio4_Desert_Island_Discs_16_January_2011_b00xgs41.flac.mp3",
      "lat": 55.9787,
      "lng": -3.6019,
      "r": 150,
      "size": 939138,
      "wild": true,
      "hint": "Politician chatting about a Walter Scott book; 33s conversational Scots accent",
      "attribution": "BBC Radio 4 Desert Island Discs (16 January 2011), via Wikimedia Commons, CC BY 3.0"
    },
    {
      "id": "wild-huddersfield-west-yorkshire-england",
      "label": "Huddersfield, West Yorkshire, England",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c6/Wilf%27_Lunn_voice_sample.wav/Wilf%27_Lunn_voice_sample.wav.mp3",
      "lat": 53.6458,
      "lng": -1.785,
      "r": 80,
      "size": 587158,
      "wild": true,
      "hint": "TV inventor interviewed at home, 28s of strong Yorkshire vowels",
      "attribution": "Interview clip by Christian Payne (Documentally), Wikimedia Commons, CC BY 4.0"
    },
    {
      "id": "wild-georgetown-south-carolina-usa-us-south",
      "label": "Georgetown, South Carolina, USA (US South)",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b8/Bill_Oberst_Jr_voice.ogg/Bill_Oberst_Jr_voice.ogg.mp3",
      "lat": 33.3768,
      "lng": -79.2945,
      "r": 400,
      "size": 821961,
      "wild": true,
      "hint": "Actor introducing himself off the cuff, 42s",
      "attribution": "Bill Oberst Jr., Wikimedia Commons (Voice intro project), CC BY-SA 4.0"
    },
    {
      "id": "wild-the-bronx-new-york-city-usa",
      "label": "The Bronx, New York City, USA",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cc/Sonia_Sotomayor_Opening_Statement_to_the_Senate_Judiciary_Committee.ogg/Sonia_Sotomayor_Opening_Statement_to_the_Senate_Judiciary_Committee.ogg.mp3",
      "lat": 40.8448,
      "lng": -73.8648,
      "r": 100,
      "size": 8515726,
      "wild": true,
      "hint": "Judge telling her life story to the Senate; 7min, NY accent; skip the first ~30s of thank-yous",
      "attribution": "US Senate Judiciary Committee hearing recording (2009), public domain"
    },
    {
      "id": "wild-boston-massachusetts-usa",
      "label": "Boston, Massachusetts, USA",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d5/JFK_inaugural_address.ogg/JFK_inaugural_address.ogg.mp3",
      "lat": 42.3601,
      "lng": -71.0589,
      "r": 120,
      "size": 11601012,
      "wild": true,
      "hint": "1961 speech, the Boston non-rhotic 'vigah' is unmistakable — but the voice is world-famous, may be too easy",
      "attribution": "John F. Kennedy Presidential Library & Museum, public domain"
    },
    {
      "id": "wild-toronto-canada",
      "label": "Toronto, Canada",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/04/Stephen_Harper_voice.ogg/Stephen_Harper_voice.ogg.mp3",
      "lat": 43.6532,
      "lng": -79.3832,
      "r": 400,
      "size": 8728589,
      "wild": true,
      "hint": "PM speaking at Davos; 6.5min, standard Canadian English",
      "attribution": "World Economic Forum 2012 recording, via Wikimedia Commons, CC BY 3.0"
    },
    {
      "id": "wild-melbourne-australia",
      "label": "Melbourne, Australia",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/53/Shelley_Segal_voice_-_en.ogg/Shelley_Segal_voice_-_en.ogg.mp3",
      "lat": -37.8136,
      "lng": 144.9631,
      "r": 500,
      "size": 584236,
      "wild": true,
      "hint": "Musician introducing herself off the cuff, 38s",
      "attribution": "Recording by Nederlandse Leeuw, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "wild-mvezo-eastern-cape-south-africa",
      "label": "Mvezo / Eastern Cape, South Africa",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1f/Nelson_Mandela_voice.ogg/Nelson_Mandela_voice.ogg.mp3",
      "lat": -31.93,
      "lng": 28.48,
      "r": 600,
      "size": 10372846,
      "wild": true,
      "hint": "10.7min speech; unmistakable cadence — world-famous voice, may be too easy",
      "attribution": "White House recording via Clinton Presidential Library, public domain"
    },
    {
      "id": "wild-mbaise-imo-state-nigeria",
      "label": "Mbaise, Imo State, Nigeria",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b2/Leo_Igwe_voice_-_en.ogg/Leo_Igwe_voice_-_en.ogg.mp3",
      "lat": 5.52,
      "lng": 7.26,
      "r": 500,
      "size": 775885,
      "wild": true,
      "hint": "Activist introducing himself, 48s, strong Nigerian English",
      "attribution": "Recording by Nederlandse Leeuw, Wikimedia Commons, CC BY-SA 4.0"
    },
    {
      "id": "wild-amritsar-punjab-india",
      "label": "Amritsar / Punjab, India",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/08/Manmohan_Singh_voice.ogg/Manmohan_Singh_voice.ogg.mp3",
      "lat": 31.634,
      "lng": 74.8723,
      "r": 800,
      "size": 1439078,
      "wild": true,
      "hint": "Indian PM addressing the US Congress, 2.5min. Note: born in pre-Partition Punjab (now Pakistan), raised in Indian Punjab",
      "attribution": "US Congress joint session recording (2005), public domain"
    },
    {
      "id": "wild-singapore",
      "label": "Singapore",
      "lang": "English",
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e5/Lawrence_Wong_on_the_Daily_Ketchup_Podcast.ogg/Lawrence_Wong_on_the_Daily_Ketchup_Podcast.ogg.mp3",
      "lat": 1.3521,
      "lng": 103.8198,
      "r": 100,
      "size": 905683,
      "wild": true,
      "hint": "PM chatting casually on a podcast, 45s of Singaporean English",
      "attribution": "The Daily Ketchup Podcast (2025), via Wikimedia Commons, CC BY 3.0"
    },
    {
      "id": "wild-texas-hill-country-stonewall-usa",
      "label": "Texas Hill Country (Stonewall), USA",
      "lang": "English",
      "url": "https://archive.org/download/lbj631101/lbj_k6311_01a_01_Goldberg.mp3",
      "lat": 30.2418,
      "lng": -98.4439,
      "r": 400,
      "size": 5940224,
      "wild": true,
      "hint": "Unscripted phone conversation, 7:08; LBJ does most of the talking but the other party (Arthur Goldberg, Chicago) also speaks.",
      "attribution": "LBJ White House telephone recordings, tape 6311.01 (Nov 1963), LBJ Presidential Library via Miller Center 'presidential_recordings' collection on Internet Archive (item lbj631101). U.S. federal government recording, public domain."
    },
    {
      "id": "wild-new-york-city-manhattan-usa",
      "label": "New York City (Manhattan), USA",
      "lang": "English",
      "url": "https://archive.org/download/EDIS-SRP-0014-17/EDIS-SRP-0014-17.mp3",
      "lat": 40.7484,
      "lng": -73.9857,
      "r": 250,
      "size": 3061867,
      "wild": true,
      "hint": "1912 campaign oration declaimed for the cylinder, 4:15; period audio quality, accent is old-fashioned upper-class New York.",
      "attribution": "Theodore Roosevelt, 'The Right of the People to Rule', Edison Blue Amberol cylinder 3707 (recorded c. Aug 1912, released Sept 1912). Digitized by NPS Thomas Edison National Historical Park (EDIS 39850); Internet Archive item EDIS-SRP-0014-17, marked public domain (pre-1923 published recording)."
    },
    {
      "id": "wild-st-ann-s-bay-jamaica",
      "label": "St. Ann's Bay, Jamaica",
      "lang": "English",
      "url": "https://archive.org/download/MarcusGarveySpeech1921/marcus_garvey_speech_1921.mp3",
      "lat": 18.4344,
      "lng": -77.1969,
      "r": 300,
      "size": 3523427,
      "wild": true,
      "hint": "Declaimed oration recorded in a studio (not read from a shared script), 3:40; 1921 disc surface noise but voice is clear.",
      "attribution": "Marcus Garvey, 'Explanation of the Objects of the Universal Negro Improvement Association', 78 rpm studio recording, New York, July 1921. Internet Archive item MarcusGarveySpeech1921, licensed public domain (published before 1923)."
    },
    {
      "id": "wild-sarnia-milton-ontario-canada",
      "label": "Sarnia / Milton, Ontario, Canada",
      "lang": "English",
      "url": "https://archive.org/download/nasa_tv-Space_Station_s_Hadfield_Connects_with_Canadian_Students/Space_Station_s_Hadfield_Connects_with_Canadian_Students.mp3",
      "lat": 43.5183,
      "lng": -79.8774,
      "r": 500,
      "size": 17519030,
      "wild": true,
      "hint": "Live unscripted Q&A downlink, 24:18 mp3; opening minutes may include Canadian event hosts (also Ontario voices) before/between Hadfield's long answers. All-English event.",
      "attribution": "NASA TV, 'Space Station's Hadfield Connects with Canadian Students', Jan 30, 2013, via Internet Archive nasa_tv collection (item nasa_tv-Space_Station_s_Hadfield_Connects_with_Canadian_Students). NASA TV production, U.S. government work, public domain."
    },
    {
      "id": "acc-london-england",
      "label": "London, England",
      "lang": "English",
      "url": "/clips/english496.mp3",
      "lat": 51.5074,
      "lng": -0.1278,
      "r": 400,
      "size": 361461,
      "hint": "SAA speaker english496, male, born in London, reading the standard 'Please call Stella' passage.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english496 (id 1724), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-manchester-england",
      "label": "Manchester, England",
      "lang": "English",
      "url": "/clips/english194.mp3",
      "lat": 53.4808,
      "lng": -2.2426,
      "r": 400,
      "size": 340217,
      "hint": "SAA speaker english194, male, born in Manchester, England.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english194 (id 638), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-glasgow-scotland",
      "label": "Glasgow, Scotland",
      "lang": "English",
      "url": "/clips/english24.mp3",
      "lat": 55.8642,
      "lng": -4.2518,
      "r": 400,
      "size": 340217,
      "hint": "SAA speaker english24, male, born in Glasgow, Scotland.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english24 (id 82), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-dublin-ireland",
      "label": "Dublin, Ireland",
      "lang": "English",
      "url": "/clips/english156.mp3",
      "lat": 53.3498,
      "lng": -6.2603,
      "r": 400,
      "size": 323081,
      "hint": "SAA speaker english156, male, born in Dublin, Ireland.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english156 (id 536), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-cardiff-wales",
      "label": "Cardiff, Wales",
      "lang": "English",
      "url": "/clips/english308.mp3",
      "lat": 51.4816,
      "lng": -3.1791,
      "r": 400,
      "size": 359026,
      "hint": "SAA speaker english308, male, born in Cardiff, Wales.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english308 (id 1101), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-fort-worth-texas-usa",
      "label": "Fort Worth, Texas, USA",
      "lang": "English",
      "url": "/clips/english157.mp3",
      "lat": 32.7555,
      "lng": -97.3308,
      "r": 400,
      "size": 303019,
      "hint": "SAA speaker english157, male, born in Fort Worth, Texas.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english157 (id 538), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-atlanta-georgia-usa",
      "label": "Atlanta, Georgia, USA",
      "lang": "English",
      "url": "/clips/english25.mp3",
      "lat": 33.749,
      "lng": -84.388,
      "r": 400,
      "size": 371146,
      "hint": "SAA speaker english25, male, born in Atlanta, Georgia.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english25 (id 83), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-new-york-city-usa",
      "label": "New York City, USA",
      "lang": "English",
      "url": "/clips/english68.mp3",
      "lat": 40.7128,
      "lng": -74.006,
      "r": 400,
      "size": 347323,
      "hint": "SAA speaker english68, male, born in New York, New York.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english68 (id 130), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-boston-massachusetts-usa",
      "label": "Boston, Massachusetts, USA",
      "lang": "English",
      "url": "/clips/english21.mp3",
      "lat": 42.3601,
      "lng": -71.0589,
      "r": 400,
      "size": 264567,
      "hint": "SAA speaker english21, female, born in Boston, Massachusetts.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english21 (id 79), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-chicago-illinois-usa",
      "label": "Chicago, Illinois, USA",
      "lang": "English",
      "url": "/clips/english82.mp3",
      "lat": 41.8781,
      "lng": -87.6298,
      "r": 400,
      "size": 357772,
      "hint": "SAA speaker english82, female, born in Chicago, Illinois.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english82 (id 146), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-los-angeles-california-usa",
      "label": "Los Angeles, California, USA",
      "lang": "English",
      "url": "/clips/english106.mp3",
      "lat": 34.0522,
      "lng": -118.2437,
      "r": 400,
      "size": 365713,
      "hint": "SAA speaker english106, female, born in Los Angeles, California.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english106 (id 408), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-toronto-canada",
      "label": "Toronto, Canada",
      "lang": "English",
      "url": "/clips/english28.mp3",
      "lat": 43.6532,
      "lng": -79.3832,
      "r": 400,
      "size": 422973,
      "hint": "SAA speaker english28, male, born in Toronto, Ontario.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english28 (id 86), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-sydney-australia",
      "label": "Sydney, Australia",
      "lang": "English",
      "url": "/clips/english84.mp3",
      "lat": -33.8688,
      "lng": 151.2093,
      "r": 400,
      "size": 362787,
      "hint": "SAA speaker english84, male, born in Sydney, Australia.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english84 (id 148), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-melbourne-australia",
      "label": "Melbourne, Australia",
      "lang": "English",
      "url": "/clips/english77.mp3",
      "lat": -37.8136,
      "lng": 144.9631,
      "r": 400,
      "size": 389954,
      "hint": "SAA speaker english77, male, born in Melbourne, Australia.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english77 (id 140), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-auckland-new-zealand",
      "label": "Auckland, New Zealand",
      "lang": "English",
      "url": "/clips/english420.mp3",
      "lat": -36.8485,
      "lng": 174.7633,
      "r": 400,
      "size": 327552,
      "hint": "SAA speaker english420, male, born in Auckland, New Zealand.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english420 (id 1387), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-cape-town-south-africa",
      "label": "Cape Town, South Africa",
      "lang": "English",
      "url": "/clips/english271.mp3",
      "lat": -33.9249,
      "lng": 18.4241,
      "r": 400,
      "size": 378252,
      "hint": "SAA speaker english271, female, born in Cape Town, South Africa.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english271 (id 904), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-mumbai-india",
      "label": "Mumbai, India",
      "lang": "English",
      "url": "/clips/english111.mp3",
      "lat": 19.076,
      "lng": 72.8777,
      "r": 400,
      "size": 351920,
      "hint": "SAA speaker english111, male, born in Bombay (Mumbai), India; a native English speaker.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english111 (id 426), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-benin-city-nigeria",
      "label": "Benin City, Nigeria",
      "lang": "English",
      "url": "/clips/english503.mp3",
      "lat": 6.335,
      "lng": 5.6037,
      "r": 400,
      "size": 589321,
      "hint": "SAA speaker english503, female, born in Benin City, Nigeria; a native English speaker.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english503 (id 1739), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-kingston-jamaica",
      "label": "Kingston, Jamaica",
      "lang": "English",
      "url": "/clips/english91.mp3",
      "lat": 17.9714,
      "lng": -76.792,
      "r": 400,
      "size": 326425,
      "hint": "SAA speaker english91, male, born in Kingston, Jamaica.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english91 (id 156), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-singapore",
      "label": "Singapore",
      "lang": "English",
      "url": "/clips/english259.mp3",
      "lat": 1.3521,
      "lng": 103.8198,
      "r": 400,
      "size": 308034,
      "hint": "SAA speaker english259, male, born in Singapore; a native English speaker.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english259 (id 870), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    },
    {
      "id": "acc-quezon-city-philippines",
      "label": "Quezon City, Philippines",
      "lang": "English",
      "url": "/clips/english140.mp3",
      "lat": 14.676,
      "lng": 121.0437,
      "r": 400,
      "size": 312214,
      "hint": "SAA speaker english140, male, born in Quezon City, Philippines; a native English speaker.",
      "attribution": "Speech Accent Archive (accent.gmu.edu), speaker english140 (id 515), CC BY-NC-SA (mirrored with attribution under CC BY-NC-SA)"
    }
  ],
  "arabic": [
    {
      "id": "ar-92",
      "label": "Djelfa, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-92.mp3",
      "lat": 34.67,
      "lng": 3.25,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Djelfa — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-249",
      "label": "Amman, Jordan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-249.mp3",
      "lat": 31.95,
      "lng": 35.93,
      "r": 350,
      "size": 481210,
      "hint": "Local radio from Amman — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-328",
      "label": "Fujairah, UAE",
      "lang": "Arabic",
      "url": "/clips/ar/ar-328.mp3",
      "lat": 25.13,
      "lng": 56.33,
      "r": 350,
      "size": 798956,
      "hint": "Local radio from Fujairah — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-679",
      "label": "Baghdad, Iraq",
      "lang": "Arabic",
      "url": "/clips/ar/ar-679.mp3",
      "lat": 33.31,
      "lng": 44.36,
      "r": 350,
      "size": 506348,
      "hint": "Local radio from Baghdad — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-809",
      "label": "Blida, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-809.mp3",
      "lat": 36.47,
      "lng": 2.83,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Blida — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-881",
      "label": "Alexandria, Egypt",
      "lang": "Arabic",
      "url": "/clips/ar/ar-881.mp3",
      "lat": 31.2,
      "lng": 29.92,
      "r": 350,
      "size": 446204,
      "hint": "Local radio from Alexandria — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1526",
      "label": "Kuwait City, Kuwait",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1526.mp3",
      "lat": 29.38,
      "lng": 47.99,
      "r": 350,
      "size": 488972,
      "hint": "Local radio from Kuwait City — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1623",
      "label": "Muscat, Oman",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1623.mp3",
      "lat": 23.59,
      "lng": 58.41,
      "r": 350,
      "size": 818540,
      "hint": "Local radio from Muscat — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1650",
      "label": "Ramallah, Palestine",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1650.mp3",
      "lat": 31.9,
      "lng": 35.2,
      "r": 350,
      "size": 480812,
      "hint": "Local radio from Ramallah — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3190",
      "label": "Nablus, Palestine",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3190.mp3",
      "lat": 32.22,
      "lng": 35.26,
      "r": 350,
      "size": 481444,
      "hint": "Local radio from Nablus — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-6196",
      "label": "Sharjah, UAE",
      "lang": "Arabic",
      "url": "/clips/ar/ar-6196.mp3",
      "lat": 25.35,
      "lng": 55.42,
      "r": 350,
      "size": 623948,
      "hint": "Local radio from Sharjah — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-6158",
      "label": "Ajman, UAE",
      "lang": "Arabic",
      "url": "/clips/ar/ar-6158.mp3",
      "lat": 25.41,
      "lng": 55.44,
      "r": 350,
      "size": 941804,
      "hint": "Local radio from Ajman — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2082",
      "label": "Algiers, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2082.mp3",
      "lat": 36.75,
      "lng": 3.06,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Algiers — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2277",
      "label": "Damascus, Syria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2277.mp3",
      "lat": 33.51,
      "lng": 36.29,
      "r": 350,
      "size": 552908,
      "hint": "Local radio from Damascus — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2316",
      "label": "Jerusalem, Palestine",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2316.mp3",
      "lat": 31.78,
      "lng": 35.22,
      "r": 350,
      "size": 878732,
      "hint": "Local radio from Jerusalem — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2375",
      "label": "Constantine, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2375.mp3",
      "lat": 36.37,
      "lng": 6.61,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Constantine — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2446",
      "label": "Beirut, Lebanon",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2446.mp3",
      "lat": 33.89,
      "lng": 35.5,
      "r": 350,
      "size": 652071,
      "hint": "Local radio from Beirut — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2787",
      "label": "Riyadh, Saudi Arabia",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2787.mp3",
      "lat": 24.71,
      "lng": 46.68,
      "r": 350,
      "size": 580556,
      "hint": "Local radio from Riyadh — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3132",
      "label": "Gaza, Palestine",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3132.mp3",
      "lat": 31.5,
      "lng": 34.47,
      "r": 350,
      "size": 947372,
      "hint": "Local radio from Gaza — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3345",
      "label": "Dubai, UAE",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3345.mp3",
      "lat": 25.2,
      "lng": 55.27,
      "r": 350,
      "size": 881579,
      "hint": "Local radio from Dubai — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3475",
      "label": "Sanaa, Yemen",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3475.mp3",
      "lat": 15.37,
      "lng": 44.19,
      "r": 350,
      "size": 619340,
      "hint": "Local radio from Sanaa — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3658",
      "label": "Tunis, Tunisia",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3658.mp3",
      "lat": 36.81,
      "lng": 10.18,
      "r": 350,
      "size": 557605,
      "hint": "Local radio from Tunis — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3785",
      "label": "Wad Medani, Sudan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3785.mp3",
      "lat": 14.4,
      "lng": 33.52,
      "r": 350,
      "size": 480620,
      "hint": "Local radio from Wad Medani — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-4531",
      "label": "Irbid, Jordan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-4531.mp3",
      "lat": 32.56,
      "lng": 35.85,
      "r": 350,
      "size": 628364,
      "hint": "Local radio from Irbid — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-6858",
      "label": "Tripoli, Libya",
      "lang": "Arabic",
      "url": "/clips/ar/ar-6858.mp3",
      "lat": 32.89,
      "lng": 13.19,
      "r": 350,
      "size": 747884,
      "hint": "Local radio from Tripoli — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2629",
      "label": "Cairo, Egypt",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2629.mp3",
      "lat": 30.04,
      "lng": 31.24,
      "r": 350,
      "size": 803564,
      "hint": "Local radio from Cairo — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-39",
      "label": "Annaba, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-39.mp3",
      "lat": 36.9,
      "lng": 7.77,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Annaba — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-423",
      "label": "Oran, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-423.mp3",
      "lat": 35.7,
      "lng": -0.63,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Oran — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-753",
      "label": "Fes, Morocco",
      "lang": "Arabic",
      "url": "/clips/ar/ar-753.mp3",
      "lat": 34.03,
      "lng": -5,
      "r": 350,
      "size": 754028,
      "hint": "Local radio from Fes — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1248",
      "label": "Manama, Bahrain",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1248.mp3",
      "lat": 26.23,
      "lng": 50.59,
      "r": 350,
      "size": 481114,
      "hint": "Local radio from Manama — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1598",
      "label": "Casablanca, Morocco",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1598.mp3",
      "lat": 33.57,
      "lng": -7.59,
      "r": 350,
      "size": 481363,
      "hint": "Local radio from Casablanca — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1733",
      "label": "Jeddah, Saudi Arabia",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1733.mp3",
      "lat": 21.49,
      "lng": 39.19,
      "r": 350,
      "size": 531068,
      "hint": "Local radio from Jeddah — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1879",
      "label": "Port Sudan, Sudan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1879.mp3",
      "lat": 19.62,
      "lng": 37.22,
      "r": 350,
      "size": 480620,
      "hint": "Local radio from Port Sudan — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-1902",
      "label": "El Obeid, Sudan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-1902.mp3",
      "lat": 13.18,
      "lng": 30.22,
      "r": 350,
      "size": 480620,
      "hint": "Local radio from El Obeid — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2473",
      "label": "Batna, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2473.mp3",
      "lat": 35.56,
      "lng": 6.17,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Batna — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-2765",
      "label": "Basra, Iraq",
      "lang": "Arabic",
      "url": "/clips/ar/ar-2765.mp3",
      "lat": 30.51,
      "lng": 47.78,
      "r": 350,
      "size": 618403,
      "hint": "Local radio from Basra — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3647",
      "label": "Tangier, Morocco",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3647.mp3",
      "lat": 35.77,
      "lng": -5.8,
      "r": 350,
      "size": 481300,
      "hint": "Local radio from Tangier — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3107",
      "label": "Benghazi, Libya",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3107.mp3",
      "lat": 32.12,
      "lng": 20.07,
      "r": 350,
      "size": 694892,
      "hint": "Local radio from Benghazi — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3433",
      "label": "Aleppo, Syria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3433.mp3",
      "lat": 36.2,
      "lng": 37.13,
      "r": 350,
      "size": 772652,
      "hint": "Local radio from Aleppo — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-5408",
      "label": "Taiz, Yemen",
      "lang": "Arabic",
      "url": "/clips/ar/ar-5408.mp3",
      "lat": 13.58,
      "lng": 44.02,
      "r": 350,
      "size": 591164,
      "hint": "Local radio from Taiz — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3735",
      "label": "Abu Dhabi, UAE",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3735.mp3",
      "lat": 24.45,
      "lng": 54.38,
      "r": 350,
      "size": 524876,
      "hint": "Local radio from Abu Dhabi — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-3854",
      "label": "Hebron, Palestine",
      "lang": "Arabic",
      "url": "/clips/ar/ar-3854.mp3",
      "lat": 31.53,
      "lng": 35.1,
      "r": 350,
      "size": 765260,
      "hint": "Local radio from Hebron — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-4464",
      "label": "Setif, Algeria",
      "lang": "Arabic",
      "url": "/clips/ar/ar-4464.mp3",
      "lat": 36.19,
      "lng": 5.41,
      "r": 350,
      "size": 481161,
      "hint": "Local radio from Setif — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    },
    {
      "id": "ar-5182",
      "label": "Omdurman, Sudan",
      "lang": "Arabic",
      "url": "/clips/ar/ar-5182.mp3",
      "lat": 15.64,
      "lng": 32.48,
      "r": 350,
      "size": 480620,
      "hint": "Local radio from Omdurman — ARCADE corpus.",
      "attribution": "ARCADE corpus (RIOTU Lab), CC BY 4.0, via Hugging Face — mirrored with attribution"
    }
  ]
};
