// Every country and region Guess Me can name, across all eight languages.
// api/languages.js decides which codes a given language is allowed to return;
// this is where the front end looks up what to display and where to fly the map.
//
// Kept separate from dialects.js because that file is the Arabic marker engine —
// this one is language-neutral reference data.

(function () {
const COUNTRIES = {
  // Every country a person might be from, ISO 3166-1 alpha-2, named the way someone would look
  // for it — "United Arab Emirates", not "Emirati"; "South Korea", not "Korea, Republic of".
  //
  // This list used to hold 79 entries, and the Arabic ones were DEMONYMS while every other block
  // used country names, because they predate the rest of the file. So the United Arab Emirates
  // sorted under E and Kuwait under K, and most of the world could not say where they were from
  // at all. The picker is the only consumer (js/app.js reads .en to build the dropdown), so the
  // lat/lng/zoom that used to sit here have gone: nothing read them, and inventing centroids for
  // two hundred countries from memory would put wrong numbers in a file that looks authoritative.
  ad: { en: "Andorra" },
  ae: { en: "United Arab Emirates" },
  af: { en: "Afghanistan" },
  ag: { en: "Antigua and Barbuda" },
  al: { en: "Albania" },
  am: { en: "Armenia" },
  ao: { en: "Angola" },
  ar: { en: "Argentina" },
  at: { en: "Austria" },
  au: { en: "Australia" },
  az: { en: "Azerbaijan" },
  ba: { en: "Bosnia and Herzegovina" },
  bb: { en: "Barbados" },
  bd: { en: "Bangladesh" },
  be: { en: "Belgium" },
  bf: { en: "Burkina Faso" },
  bg: { en: "Bulgaria" },
  bh: { en: "Bahrain" },
  bi: { en: "Burundi" },
  bj: { en: "Benin" },
  bn: { en: "Brunei" },
  bo: { en: "Bolivia" },
  br: { en: "Brazil" },
  bs: { en: "Bahamas" },
  bt: { en: "Bhutan" },
  bw: { en: "Botswana" },
  by: { en: "Belarus" },
  bz: { en: "Belize" },
  ca: { en: "Canada" },
  cd: { en: "Congo (DRC)" },
  cf: { en: "Central African Republic" },
  cg: { en: "Congo" },
  ch: { en: "Switzerland" },
  ci: { en: "Côte d'Ivoire" },
  cl: { en: "Chile" },
  cm: { en: "Cameroon" },
  cn: { en: "China" },
  co: { en: "Colombia" },
  cr: { en: "Costa Rica" },
  cu: { en: "Cuba" },
  cv: { en: "Cape Verde" },
  cy: { en: "Cyprus" },
  cz: { en: "Czechia" },
  de: { en: "Germany" },
  dj: { en: "Djibouti" },
  dk: { en: "Denmark" },
  dm: { en: "Dominica" },
  do: { en: "Dominican Republic" },
  dz: { en: "Algeria" },
  ec: { en: "Ecuador" },
  ee: { en: "Estonia" },
  eg: { en: "Egypt" },
  er: { en: "Eritrea" },
  es: { en: "Spain" },
  et: { en: "Ethiopia" },
  fi: { en: "Finland" },
  fj: { en: "Fiji" },
  fm: { en: "Micronesia" },
  fr: { en: "France" },
  ga: { en: "Gabon" },
  gb: { en: "United Kingdom" },
  gd: { en: "Grenada" },
  ge: { en: "Georgia" },
  gh: { en: "Ghana" },
  gm: { en: "Gambia" },
  gn: { en: "Guinea" },
  gq: { en: "Equatorial Guinea" },
  gr: { en: "Greece" },
  gt: { en: "Guatemala" },
  gw: { en: "Guinea-Bissau" },
  gy: { en: "Guyana" },
  hk: { en: "Hong Kong" },
  hn: { en: "Honduras" },
  hr: { en: "Croatia" },
  ht: { en: "Haiti" },
  hu: { en: "Hungary" },
  id: { en: "Indonesia" },
  ie: { en: "Ireland" },
  il: { en: "Israel" },
  in: { en: "India" },
  iq: { en: "Iraq" },
  ir: { en: "Iran" },
  is: { en: "Iceland" },
  it: { en: "Italy" },
  jm: { en: "Jamaica" },
  jo: { en: "Jordan" },
  jp: { en: "Japan" },
  ke: { en: "Kenya" },
  kg: { en: "Kyrgyzstan" },
  kh: { en: "Cambodia" },
  ki: { en: "Kiribati" },
  km: { en: "Comoros" },
  kn: { en: "Saint Kitts and Nevis" },
  kp: { en: "North Korea" },
  kr: { en: "South Korea" },
  kw: { en: "Kuwait" },
  kz: { en: "Kazakhstan" },
  la: { en: "Laos" },
  lb: { en: "Lebanon" },
  lc: { en: "Saint Lucia" },
  li: { en: "Liechtenstein" },
  lk: { en: "Sri Lanka" },
  lr: { en: "Liberia" },
  ls: { en: "Lesotho" },
  lt: { en: "Lithuania" },
  lu: { en: "Luxembourg" },
  lv: { en: "Latvia" },
  ly: { en: "Libya" },
  ma: { en: "Morocco" },
  mc: { en: "Monaco" },
  md: { en: "Moldova" },
  me: { en: "Montenegro" },
  mg: { en: "Madagascar" },
  mh: { en: "Marshall Islands" },
  mk: { en: "North Macedonia" },
  ml: { en: "Mali" },
  mm: { en: "Myanmar" },
  mn: { en: "Mongolia" },
  mo: { en: "Macau" },
  mr: { en: "Mauritania" },
  mt: { en: "Malta" },
  mu: { en: "Mauritius" },
  mv: { en: "Maldives" },
  mw: { en: "Malawi" },
  mx: { en: "Mexico" },
  my: { en: "Malaysia" },
  mz: { en: "Mozambique" },
  na: { en: "Namibia" },
  ne: { en: "Niger" },
  ng: { en: "Nigeria" },
  ni: { en: "Nicaragua" },
  nl: { en: "Netherlands" },
  no: { en: "Norway" },
  np: { en: "Nepal" },
  nr: { en: "Nauru" },
  nz: { en: "New Zealand" },
  om: { en: "Oman" },
  pa: { en: "Panama" },
  pe: { en: "Peru" },
  pg: { en: "Papua New Guinea" },
  ph: { en: "Philippines" },
  pk: { en: "Pakistan" },
  pl: { en: "Poland" },
  pr: { en: "Puerto Rico" },
  ps: { en: "Palestine" },
  pt: { en: "Portugal" },
  pw: { en: "Palau" },
  py: { en: "Paraguay" },
  qa: { en: "Qatar" },
  ro: { en: "Romania" },
  rs: { en: "Serbia" },
  ru: { en: "Russia" },
  rw: { en: "Rwanda" },
  sa: { en: "Saudi Arabia" },
  sb: { en: "Solomon Islands" },
  sc: { en: "Seychelles" },
  sd: { en: "Sudan" },
  se: { en: "Sweden" },
  sg: { en: "Singapore" },
  si: { en: "Slovenia" },
  sk: { en: "Slovakia" },
  sl: { en: "Sierra Leone" },
  sm: { en: "San Marino" },
  sn: { en: "Senegal" },
  so: { en: "Somalia" },
  sr: { en: "Suriname" },
  ss: { en: "South Sudan" },
  st: { en: "São Tomé and Príncipe" },
  sv: { en: "El Salvador" },
  sy: { en: "Syria" },
  sz: { en: "Eswatini" },
  td: { en: "Chad" },
  tg: { en: "Togo" },
  th: { en: "Thailand" },
  tj: { en: "Tajikistan" },
  tl: { en: "Timor-Leste" },
  tm: { en: "Turkmenistan" },
  tn: { en: "Tunisia" },
  to: { en: "Tonga" },
  tr: { en: "Türkiye" },
  tt: { en: "Trinidad and Tobago" },
  tv: { en: "Tuvalu" },
  tw: { en: "Taiwan" },
  tz: { en: "Tanzania" },
  ua: { en: "Ukraine" },
  ug: { en: "Uganda" },
  us: { en: "United States" },
  uy: { en: "Uruguay" },
  uz: { en: "Uzbekistan" },
  va: { en: "Vatican City" },
  vc: { en: "Saint Vincent and the Grenadines" },
  ve: { en: "Venezuela" },
  vn: { en: "Vietnam" },
  vu: { en: "Vanuatu" },
  ws: { en: "Samoa" },
  xk: { en: "Kosovo" },
  ye: { en: "Yemen" },
  za: { en: "South Africa" },
  zm: { en: "Zambia" },
  zw: { en: "Zimbabwe" },
};

const REGIONS = {
  // Arabic
  egyptian: { en: 'Egyptian', ar: 'مصرية' },
  levantine: { en: 'Levantine', ar: 'شامية' },
  iraqi: { en: 'Iraqi', ar: 'عراقية' },
  gulf: { en: 'Gulf', ar: 'خليجية' },
  yemeni: { en: 'Yemeni', ar: 'يمنية' },
  sudanese: { en: 'Sudanese', ar: 'سودانية' },
  maghrebi: { en: 'Maghrebi', ar: 'مغاربية' },
  // Spanish
  peninsular: { en: 'Peninsular' },
  rioplatense: { en: 'Rioplatense' },
  mexican: { en: 'Mexican' },
  andean: { en: 'Andean' },
  caribbean: { en: 'Caribbean' },
  chilean: { en: 'Chilean' },
  centralamerican: { en: 'Central American' },
  // French
  metropolitan: { en: 'Metropolitan French' },
  quebecois: { en: 'Québécois' },
  belgian: { en: 'Belgian' },
  swiss: { en: 'Swiss' },
  westafrican: { en: 'West African' },
  eastafrican: { en: 'East African' },
  // Portuguese
  brazilian: { en: 'Brazilian' },
  european: { en: 'European Portuguese' },
  angolan: { en: 'Angolan' },
  mozambican: { en: 'Mozambican' },
  capeverdean: { en: 'Cape Verdean' },
  // Russian
  central: { en: 'Central Russian' },
  northwest: { en: 'Northwestern (Petersburg)' },
  southern: { en: 'Southern Russian' },
  siberian: { en: 'Siberian' },
  ukrainian: { en: 'Ukrainian Russian' },
  belarusian: { en: 'Belarusian' },
  centralasian: { en: 'Central Asian' },
  caucasus: { en: 'Caucasus' },
  diaspora: { en: 'Diaspora' },
  // Hindi–Urdu
  hindi: { en: 'Hindi register' },
  urdu: { en: 'Urdu register' },
  bambaiya: { en: 'Bambaiya (Mumbai)' },
  punjabi: { en: 'Punjabi-influenced' },
  hyderabadi: { en: 'Hyderabadi' },
  dakhini: { en: 'Dakhini' },
  // Chinese
  mainland: { en: 'Mainland Mandarin' },
  taiwan: { en: 'Taiwan Mandarin' },
  cantonese: { en: 'Cantonese' },
  singapore: { en: 'Singapore' },
  northern: { en: 'Northern' },
  // English
  american: { en: 'American' },
  canadian: { en: 'Canadian' },
  english: { en: 'English (England)' },
  scottish: { en: 'Scottish' },
  welsh: { en: 'Welsh' },
  irish: { en: 'Irish' },
  australasian: { en: 'Australian / NZ' },
  southafrican: { en: 'South African' },
  southasian: { en: 'South Asian' },
  seasian: { en: 'Southeast Asian' },
  // shared
  msa: { en: 'Standard' },
  neutral: { en: 'Neutral' },
};

window.HT_PLACES = { COUNTRIES, REGIONS };
}());
